/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Manager.formnhanvien;

import java.awt.Color;
import java.awt.Component;
import java.lang.System.Logger;
import java.sql.SQLException;
import java.util.regex.Pattern;
import javaapplication1.Login.dangky;
import javaapplication1.database.SQLServerConnection;
import javax.swing.JOptionPane;

/**
 *
 * @author vuwin
 */
public class add extends javax.swing.JPanel {

    /**
     * Creates new form add
     */
    public add() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        error5 = new javax.swing.JLabel();
        error6 = new javax.swing.JLabel();
        textUsername = new javax.swing.JTextField();
        error7 = new javax.swing.JLabel();
        textPassword = new javax.swing.JTextField();
        DayCombox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        MonthCombox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        YearCombox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textNumber = new javax.swing.JLabel();
        creaateacc = new javax.swing.JButton();
        checkdk = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtAdress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCCCD = new javax.swing.JTextField();
        error1 = new javax.swing.JLabel();
        error2 = new javax.swing.JLabel();
        textname = new javax.swing.JTextField();
        error3 = new javax.swing.JLabel();
        textEmail = new javax.swing.JTextField();
        error4 = new javax.swing.JLabel();
        textsdt = new javax.swing.JTextField();
        textConfirm = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 587));

        error5.setForeground(new java.awt.Color(255, 255, 255));
        error5.setText(".");

        error6.setForeground(new java.awt.Color(255, 255, 255));
        error6.setText(".");

        textUsername.setMinimumSize(new java.awt.Dimension(450, 22));
        textUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textUsernameActionPerformed(evt);
            }
        });

        error7.setForeground(new java.awt.Color(255, 255, 255));
        error7.setText(".");

        textPassword.setMinimumSize(new java.awt.Dimension(450, 22));

        DayCombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        DayCombox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DayComboxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 3, 48)); // NOI18N
        jLabel1.setText("REGISTER");

        MonthCombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        MonthCombox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonthComboxActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("MV Boli", 3, 14)); // NOI18N
        jLabel2.setText("Name :");

        YearCombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setFont(new java.awt.Font("MV Boli", 3, 14)); // NOI18N
        jLabel3.setText("Email :");

        jLabel4.setFont(new java.awt.Font("MV Boli", 3, 14)); // NOI18N
        jLabel4.setText("Username :");

        jLabel5.setFont(new java.awt.Font("MV Boli", 3, 14)); // NOI18N
        jLabel5.setText("Password :");

        jLabel6.setFont(new java.awt.Font("MV Boli", 3, 14)); // NOI18N
        jLabel6.setText("Confirm Password :");

        textNumber.setFont(new java.awt.Font("MV Boli", 3, 14)); // NOI18N
        textNumber.setText("Number Phone :");

        creaateacc.setFont(new java.awt.Font("MV Boli", 3, 18)); // NOI18N
        creaateacc.setText("Create");
        creaateacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creaateaccActionPerformed(evt);
            }
        });

        checkdk.setFont(new java.awt.Font("MV Boli", 3, 12)); // NOI18N
        checkdk.setText("Agree to the Terms of Service and Privacy Policy.");
        checkdk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkdkActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("MV Boli", 3, 14)); // NOI18N
        jLabel7.setText("Date Of Birth :");

        jLabel8.setFont(new java.awt.Font("MV Boli", 3, 14)); // NOI18N
        jLabel8.setText("CCCD  :");

        txtAdress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdressActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("MV Boli", 3, 14)); // NOI18N
        jLabel9.setText("Adress  :");

        txtCCCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCCCDActionPerformed(evt);
            }
        });

        error1.setForeground(new java.awt.Color(255, 255, 255));

        error2.setForeground(new java.awt.Color(255, 255, 255));

        textname.setMinimumSize(new java.awt.Dimension(450, 22));
        textname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textnameActionPerformed(evt);
            }
        });

        error3.setForeground(new java.awt.Color(255, 255, 255));
        error3.setText(".");

        textEmail.setMinimumSize(new java.awt.Dimension(450, 22));
        textEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEmailActionPerformed(evt);
            }
        });

        error4.setForeground(new java.awt.Color(255, 255, 255));
        error4.setText(".");

        textsdt.setMinimumSize(new java.awt.Dimension(450, 22));
        textsdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textsdtActionPerformed(evt);
            }
        });

        textConfirm.setMinimumSize(new java.awt.Dimension(450, 22));

        jLabel10.setText("jLabel10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(error5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(196, 196, 196))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(textname, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(error2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(61, 61, 61))
                                            .addComponent(error3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(156, 156, 156))
                                    .addComponent(error4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(36, 36, 36)))
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(DayCombox, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(MonthCombox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(YearCombox, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(textNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(textsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(txtCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(148, 148, 148)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(textPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(121, 121, 121))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(515, 515, 515)
                            .addComponent(error7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(365, 365, 365)
                            .addComponent(creaateacc, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(error6, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(623, 623, 623)
                            .addComponent(error1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(checkdk)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(error2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(error3)
                    .addComponent(jLabel5)
                    .addComponent(textPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(error4)
                    .addComponent(jLabel6)
                    .addComponent(textConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(MonthCombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DayCombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YearCombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNumber)
                    .addComponent(textsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(error5)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(checkdk))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(error1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(error6)
                    .addComponent(creaateacc))
                .addGap(38, 38, 38)
                .addComponent(error7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textUsernameActionPerformed

    private void DayComboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DayComboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DayComboxActionPerformed

    private void MonthComboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonthComboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MonthComboxActionPerformed

    private void creaateaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creaateaccActionPerformed
        Component frame = null;
        SQLServerConnection dbConnection = new SQLServerConnection();
        if (dbConnection.connect() == null) {
            JOptionPane.showMessageDialog(null,"loi ket noi,vui long kiem tra lai mang cua b\n");
        }
        String Thongbao = new String();
        String name = textname.getText().trim();
        if(name.equals("")){
            Thongbao += "Bạn chưa nhập tên!\n";
            error1.setText("Bạn chưa nhập tên!\n");
            error1.setForeground(Color.red);
        }
        else{
            textname.setBackground(Color.white);
        }
        String Email = new String(textEmail.getText()).trim();
        // Biểu thức chính quy kiểm tra định dạng email
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@" +
        "(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
        Pattern pattern = Pattern.compile(emailRegex);
        boolean chuan = pattern.matcher(Email).matches();
        if(chuan){
            textEmail.setBackground(Color.white);
            //            JOptionPane.showMessageDialog(this, "Đăng ký thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            String retrievedEmail = dbConnection.getEmail("NhanVien");
            if (retrievedEmail != null && retrievedEmail.equals(Email)) {
                Thongbao += "Đã tồn tại Email!\n";
                error2.setText("Đã tồn tại Email!\n");
                error2.setForeground(Color.red);
            } else if (retrievedEmail == null) {
                System.out.println("Không tìm thấy email trong cơ sở dữ liệu.");
                // Hoặc có thể xử lý khác nếu cần
            }

        }
        else{
            if(Email.equals("")){
                error2.setText("Bạn chưa nhập Email!\n");
                error2.setForeground(Color.red);
            }
            else{
                textEmail.setBackground(Color.red);
                Thongbao += "Bạn nhập sai kiểu Email!\n";
                error2.setText("Bạn nhập sai kiểu Email!\n");
                error2.setForeground(Color.red);
            }
            //            JOptionPane.showMessageDialog(this, "Email không hợp lệ!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }

        String adress = txtAdress.getText();

        String username = textUsername.getText().trim();
        if(username.equals("")){
            textUsername.setBackground(Color.red);
            Thongbao += "Bạn chưa nhập Username!\n";
            error3.setText("Bạn chưa nhập Username!\n");
            error3.setForeground(Color.red);
        }
        else{
            textUsername.setBackground(Color.white);
            try {
                if(dbConnection.kiemtraUsername("NhanVien",username)!= null ){
                    Thongbao += "Đã tồn tại tài khoản!\n";
                    error3.setText("Đã tồn tại tài khoản!\n");
                    error3.setForeground(Color.red);
                }   
            }
                catch (SQLException e) {
                e.printStackTrace();
            }
            }
            String password = new String(textPassword.getText());
            String Confirm = new String(textConfirm.getText());
            if (password.equals(Confirm) && !password.equals("")) {
                // Nếu mật khẩu và xác nhận khớp và không trống
                textPassword.setBackground(Color.white);
                textConfirm.setBackground(Color.white);
            } else if (Confirm.equals("") || password.equals("")) {
                // Nếu một trong hai trường mật khẩu hoặc xác nhận mật khẩu bị bỏ trống
                Thongbao += "Bạn chưa nhập mật khẩu!\n";
                error4.setText("Bạn chưa nhập mật khẩu!\n");
                error4.setForeground(Color.red);
                error5.setText("Bạn chưa nhập mật khẩu!\n");
                error5.setForeground(Color.red);
            } else {
                // Nếu mật khẩu và xác nhận không khớp
                error4.setText("Bạn nhập mật khẩu không khớp!\n");
                error4.setForeground(Color.red);
                error5.setText("Bạn nhập mật khẩu không khớp!\n");
                error5.setForeground(Color.red);
                Thongbao += "Bạn nhập mật khẩu không khớp!\n";
            }
            // ngay thang nam sinh
            String ngay = (String)DayCombox.getSelectedItem();
            String thang = (String)MonthCombox.getSelectedItem();
            String nam = (String)YearCombox.getSelectedItem();
            String sinhnhat = ngay + '/' + thang + '/' + nam;

            // chuc vu
            String numbers = textsdt.getText().trim();

            if (numbers.length() == 11 && numbers.matches("\\d+")) {
                textNumber.setBackground(Color.white);
            }
            else if(numbers.equals("")){
                error6.setText("Bạn chưa nhập số điện thoại");
                error6.setForeground(Color.red);
                Thongbao += "Bạn chưa nhập số điện thoại";
            } else {
                textNumber.setBackground(Color.red);
                error6.setForeground(Color.red);
                error6.setText("Bạn nhập không đủ 11 số hoặc có kèm ký tự");
                Thongbao += "Bạn nhập không đủ 11 số hoặc có kèm ký tự";
                //           JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ. Vui lòng nhập đúng 11 số và không chứa khoảng trắng.", "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
            }
            String cccd = txtCCCD.getText();
            if(!dbConnection.kiemtracccd("NhanVien",cccd)){
                error7.setForeground(Color.red);
                error7.setText("Căn cước công dân đã tồn tại!");
                Thongbao += "Căn cước công dân đã tồn tại!";
            }

            boolean agree = checkdk.isSelected();
            if(agree==false){
                Thongbao += "Bạn chưa đồng ý bảo mật!\n";
            }
            if(Thongbao.equals("")){
                JOptionPane.showMessageDialog(this, "Đăng ký thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(this,"Đăng ký thất bại!" , "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_creaateaccActionPerformed

    private void checkdkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkdkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkdkActionPerformed

    private void txtAdressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdressActionPerformed

    private void txtCCCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCCCDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCCCDActionPerformed

    private void textnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textnameActionPerformed

    }//GEN-LAST:event_textnameActionPerformed

    private void textEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEmailActionPerformed

    }//GEN-LAST:event_textEmailActionPerformed

    private void textsdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textsdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textsdtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> DayCombox;
    private javax.swing.JComboBox<String> MonthCombox;
    private javax.swing.JComboBox<String> YearCombox;
    private javax.swing.JCheckBox checkdk;
    private javax.swing.JButton creaateacc;
    private javax.swing.JLabel error1;
    private javax.swing.JLabel error2;
    private javax.swing.JLabel error3;
    private javax.swing.JLabel error4;
    private javax.swing.JLabel error5;
    private javax.swing.JLabel error6;
    private javax.swing.JLabel error7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField textConfirm;
    private javax.swing.JTextField textEmail;
    private javax.swing.JLabel textNumber;
    private javax.swing.JTextField textPassword;
    private javax.swing.JTextField textUsername;
    private javax.swing.JTextField textname;
    private javax.swing.JTextField textsdt;
    private javax.swing.JTextField txtAdress;
    private javax.swing.JTextField txtCCCD;
    // End of variables declaration//GEN-END:variables
}
